name: Deploy static content to Pages

# run on completed test website workflow run (and allow manual dispatch)
on:
  workflow_run:
    workflows: ["Test Website"]
    types: [completed]
  workflow_dispatch:

# grant the token permission to push your site
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure Pages
        uses: actions/configure-pages@v4
        
      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the root directory (static files)
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
